#!/usr/bin/php
<?php
/**
* Orchestra Script 
*
*
* Licensed under the MIT license.
*
* @category   Orchestra
* @copyright  Copyright (c) 2010, Christopher Hein
* @license    http://orchestramvc.chrishe.in/license
* @version    Release: 0.0.1:beta
* @link       http://orchestramvc.chrishe.in/docs/script/orchestra/
*
*/

	// Variables
$fpath = getcwd();

if($argv[1] == '--help' || $argv[1] == '') {
	$file = include('/usr/local/orchestra/man/scripts/instrument');
	echo $file;
} else if($argv[1] == 'install') {
	$instrument = $argv[2];
	echo "\nInstalling \n";
	exec("cp -rf /usr/local/orchestra/instruments/".$instrument.".instrument ".$fpath."/instruments/".$instrument.".instrument ; cd instruments/ ; unzip ".$instrument.".instrument ; cd ../ ;");
	echo "Copied original to ./instruments/ \n";
	echo "Installing Components\n";
	exec("php instruments/".$instrument."/install play ;");
	$file = include("instruments/".$instrument."/README");
	echo "\n".$file."\n\n";
	$type = explode('-', $instrument);
	$open = fopen('instruments.orc', 'a');
	$data = '
$orchestra[\''.$type[1].'\']  = \''.$instrument.'\';
';
	$write = fwrite($open, $data);
	$close = fclose($open);
	echo "\n\t EDITED :: instruments.orc";
	echo "\n \n Finished\n";
	exec("rm -rf instruments/".$instrument."/ ;");
	
} else if($argv[1] == 'pull') {
	if(isset($argv[2])) {
		echo "\nGetting Resources \n";
		$url = "git://github.com/christopherhein/".$argv[2].".instrument.git";
		exec("cd /usr/local/orchestra/instruments/ ; git clone $url ;");
		echo "\nFinished Pulling \n";
		exec("cd /usr/local/orchestra/instruments/ ; mv ".$argv[2].".instrument/ ./".$argv[2]."/ ;");
		exec("cd /usr/local/orchestra/instruments/ ; mv ".$argv[2]."/".$argv[2].".instrument ./".$argv[2].".instrument ;");
		echo "Moved Source \n";
		exec("cd /usr/local/orchestra/instruments/ ; rm -rf ".$argv[2]."/ ;");
		echo "Removed Uncompiled Source \n";
	} else {
		echo "\nPlease specify an addon to find \n\n";
	}
} else if($argv[1] == 'build') {
	if(isset($argv[2])) {
		echo "\nBuilding Instrument\n";
		exec("zip -r $argv[2] $argv[2]/* ;");
		echo "Bundled instrument\n";
		exec("mv $argv[2].zip $argv[2].instrument ;");
		echo "All finihed! \n\n";
	}
} else if($argv[1] == '') {
	echo "\nYou need an instrument name \n";
}