#!/usr/bin/php
<?php
/**
* Orchestra Script 
*
* Fired from thw CMD Line using 'php script/deploy'
* Variables may be passed in for db merging and db rebuilding on the live server
*
* Dual licensed under the MIT or GPL Version 2 licenses.
*
* @category   Orchestra
* @copyright  Copyright (c) 2010, Christopher Hein
* @license    http://orchestramvc.chrishe.in/license
* @version    Release: 0.0.1:beta
* @link       http://orchestramvc.chrishe.in/docs/script/orchestra/
*
*/

	// Variables
$fpath = getcwd();
$app = $argv[2];

if($argv[1] == '--help' || $argv[1] == '') {
	$file = include('/usr/local/orchestra/man/scripts/admin');
	echo $file;
} else if($argv[1] == 'new') {
	exec("cp -rf /usr/local/orchestra/app/ ".$fpath."/".$app."/ ; cd ".$app."/ ;");
	
	echo "\n New App Created ".$app."/ \n\n";
	
} else if($argv[2] == '') {
	echo "\n You need and application name \n";
}