#!/usr/bin/php
<?php
/**
* Deploy Script 
*
* Fired from thw CMD Line using 'php script/deploy'
* Variables may be passed in for db merging and db rebuilding on the live server
*
* Licensed under the MIT license.
*
* @category   Orchestra
* @copyright  Copyright (c) 2010, Christopher Hein
* @license    http://orchestramvc.chrishe.in/license
* @version    Release: 0.0.1:beta
* @link       http://orchestramvc.chrishe.in/docs/script/deploy/
*
*/
require(dirname(dirname(__FILE__)).'/config/definitions.php');

if($argv[1] == '--help' || $argv[1] == '') {

	$file = include('/usr/local/orchestra/man/scripts/generate');
	echo $file;

} else if($argv[1] == 'controller') {
	
	$page = strtolower($argv[2]);
	$controller = CONTROLLERS.$page.'_controller.php';
	$helper = HELPERS.$page.'_helper.php';
	$routes = CONFIG.'routes.php';
	if(isset($argv[3])) {
		$action_array = array();
		$action = strtolower($argv[3]);
		$action_array = split(",", $action);
	} else { 
		$action = "index";
	}
	unlink($controller);
	unlink($helper);
	foreach($action_array as $a) {
		unlink(VIEWS.$page.'/'.$a.'.html.orc');
	}
	rmdir(VIEWS.$page.'/');
} else if($argv[1] == 'resource') {
	
}


